### ISSUE TITLE
(1) Unable to set fees for binance account and (2) Unexpected Error occured when attempting to buy

### ISSUE THREAD

**Issue by jdk-sal3** [Syycoker/Automatic-Trade-Bot#2]
Hi, thanks for sharing this code.

I tried to run it:

Reading authentication file...
Checking Authorisation keys...
Authentication Initialised.
-------------------------------------------------------------------------

Program Starting...
Collecting all tradeable assets in the marketplace...
Unable to set fees for binance account.
Analysing: 'ETHBTC'.
Analysing: 'LTCBTC'.
Buying asset: 'LTCBTC' .
Unexpected Error occured when attempting to buy: 'LTCBTC'.

I'm not a programmer so I don't really know how to fix this. I hope you can show me the work around. Thanks

**Comment by jdk-sal3** [comment]
Never mind, I put API with wrong permission. It's solved.

**Comment by Syycoker** [comment]
Glad the issue was resolved.
